import React from 'react'
import Head from "next/head";
import LeftAside from './LeftAside';
import RightAside from './RightAside';
import Footer from './Footer';
import Header from './Header';

const CommonLayout = ({children}) => {
  return (
    <>
      <div className="container p-0">
        <Head>
          <title>The City App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <main className="p-4">
          <div className="row">
            <LeftAside />
            {children}
            
            <RightAside />
          </div>
        </main>
        <Footer />
      </div>
    </>
  );
}

export default CommonLayout
